EVALUATE
GROUPBY (
    FILTER (
        ADDCOLUMNS (
            SUMMARIZE ( 'fct Auditlogs', 'dim Gebruiker'[UserId - Copy], 'dim Datum'[Date] ),
            "@CALC", [view]
        ),
        NOT ISBLANK ( [@CALC] ) && 'dim Gebruiker'[UserId - Copy] = "victor.baelus@vrt.be"
    ),
    'dim Gebruiker'[UserId - Copy] //'dim Datum'[Date],
    ,
    "days_with_activity", COUNTX ( CURRENTGROUP (), [@CALC] ),
    "total_activity", SUMX ( CURRENTGROUP (), [@CALC] ),
    "average_activity_per_day", AVERAGEX ( CURRENTGROUP (), [@CALC] ),
    "max_activity_per_day", MAXX ( CURRENTGROUP (), [@CALC] )
)
ORDER BY 'dim Gebruiker'[UserId - Copy] DESC
//,    'dim Datum'[Date] ASC